=== Urielakerhub/Dise-o-y-validaci-n-de-resultados-de-Liga-MX-con-XML-y-DTD/dtd/resultados.dtd
<!ELEMENT liga (jornada+)>
<!ATTLIST liga
    temporada CDATA #REQUIRED
    competencia CDATA #REQUIRED
>

<!ELEMENT jornada (partido+)>
<!ATTLIST jornada
    numero CDATA #REQUIRED
    fecha CDATA #REQUIRED
>

<!ELEMENT partido (equipoLocal, equipoVisitante, marcador, estadisticas?)>
<!ATTLIST partido
    id ID #REQUIRED
    fecha CDATA #REQUIRED
    estadio CDATA #IMPLIED
    estado CDATA #REQUIRED
>

<!ELEMENT equipoLocal (nombre)>
<!ELEMENT equipoVisitante (nombre)>
<!ELEMENT nombre (#PCDATA)>

<!ELEMENT marcador (golesLocal, golesVisitante)>
<!ELEMENT golesLocal (#PCDATA)>
<!ELEMENT golesVisitante (#PCDATA)>

<!ELEMENT estadisticas (local, visitante)>
<!ELEMENT local (posesion?, tiros?, tirosPuerta?, faltas?, tarjetas?, tirosEsquina?)>
<!ELEMENT visitante (posesion?, tiros?, tirosPuerta?, faltas?, tarjetas?, tirosEsquina?)>

<!ELEMENT posesion (#PCDATA)>
<!ELEMENT tiros (#PCDATA)>
<!ELEMENT tirosPuerta (#PCDATA)>
<!ELEMENT faltas (#PCDATA)>
<!ELEMENT tarjetas (tarjeta*)>
<!ELEMENT tarjeta (#PCDATA)>
<!ELEMENT tirosEsquina (#PCDATA)>

=== Urielakerhub/Dise-o-y-validaci-n-de-resultados-de-Liga-MX-con-XML-y-DTD/xml/resultados.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "../dtd/resultados.dtd">
<liga temporada="Apertura 2026" competencia="Liga MX">
    <jornada numero="10" fecha="2026-09-27">

        <partido id="P001" fecha="2026-09-27" estadio="Estadio Olímpico Universitario" estado="Finalizado">
            <equipoLocal>
                <nombre>Pumas</nombre>
            </equipoLocal>
            <equipoVisitante>
                <nombre>Atlético San Luis</nombre>
            </equipoVisitante>
            <marcador>
                <golesLocal>2</golesLocal>
                <golesVisitante>3</golesVisitante>
            </marcador>
        </partido>

        <partido id="P002" fecha="2026-09-27" estadio="Estadio Universitario" estado="Finalizado">
            <equipoLocal>
                <nombre>Tigres</nombre>
            </equipoLocal>
            <equipoVisitante>
                <nombre>Puebla</nombre>
            </equipoVisitante>
            <marcador>
                <golesLocal>1</golesLocal>
                <golesVisitante>0</golesVisitante>
            </marcador>
        </partido>

        <partido id="P003" fecha="2026-09-27" estadio="Estadio Corona" estado="Finalizado">
            <equipoLocal>
                <nombre>Santos Laguna</nombre>
            </equipoLocal>
            <equipoVisitante>
                <nombre>Pachuca</nombre>
            </equipoVisitante>
            <marcador>
                <golesLocal>1</golesLocal>
                <golesVisitante>0</golesVisitante>
            </marcador>
        </partido>

    </jornada>
</liga>

=== Urielakerhub/Dise-o-y-validaci-n-de-resultados-de-Liga-MX-con-XML-y-DTD/xml/resultados-invalido.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE liga SYSTEM "../dtd/resultados.dtd">
<liga temporada="Apertura 2026" competencia="Liga MX">
    <jornada numero="10" fecha="2026-09-27">
        <partido id="P001" fecha="2026-09-27" estadio="Estadio Olímpico Universitario" estado="Finalizado">
            <equipoLocal>
                <nombre>Pumas</nombre>
            </equipoLocal>
            <!-- ERROR INTENCIONAL: falta equipoVisitante -->
            <marcador>
                <golesLocal>2</golesLocal>
                <golesVisitante>3</golesVisitante>
            </marcador>
        </partido>
    </jornada>
</liga>
